import json
import os

# Type codes (compact)
TYPE_CODE = {
    "Rest- & Biomüll": "R",
    "Gelber Sack":     "G",
    "Papiertonne":     "P",
    "Grüngut":         "B",  # Braun (only used if a future PDF adds it)
}

events_by_bezirk = json.load(open("/tmp/abfall2026_events.json"))

ts_lines = [
    "/**",
    " * lib/calendar2026.ts",
    " *",
    " * Built-in fallback calendar for Neu-Ulm 2026 — extracted from the official",
    " * Stadt Neu-Ulm Abfallkalender PDF (Nov 2025 issue). Compact per-Bezirk",
    " * arrays of [yyyy-mm-dd, type-code] tuples.",
    " *",
    " *   Type codes: R = Rest- & Biomüll, G = Gelber Sack, P = Papiertonne, B = Grüngut",
    " *",
    " * Generated by scripts/build_calendar.py — do not edit by hand.",
    " */",
    "",
    "export type CompactType = \"R\" | \"G\" | \"P\" | \"B\";",
    "export type CompactEvent = readonly [string, CompactType];",
    "",
    "export const CALENDAR_2026: Readonly<Record<number, readonly CompactEvent[]>> = {",
]

for b in range(1, 9):
    evs = events_by_bezirk[str(b)]
    pairs = []
    for date_str, typ in evs:
        code = TYPE_CODE.get(typ, "?")
        pairs.append(f'["{date_str}","{code}"]')
    ts_lines.append(f"  {b}: [")
    # group 4 per line for readability
    for i in range(0, len(pairs), 4):
        chunk = ", ".join(pairs[i:i+4])
        ts_lines.append(f"    {chunk},")
    ts_lines.append("  ],")
ts_lines.append("};")
ts_lines.append("")

ts_lines += [
    "/** Reverse map for the parser. */",
    "const TYPE_BY_CODE: Record<CompactType, string> = {",
    '  R: "Rest- & Biomüll",',
    '  G: "Gelber Sack",',
    '  P: "Papiertonne",',
    '  B: "Grüngut",',
    "};",
    "",
    "/**",
    " * Build a minimal RFC 5545 ICS string for the requested Bezirk on demand.",
    " * Used as the absolute last-resort calendar fallback in dataFetcher.",
    " */",
    "export function buildBuiltinIcs(bezirk: number): string {",
    "  const events = CALENDAR_2026[bezirk];",
    "  if (!events) return \"\";",
    "  const out: string[] = [",
    "    \"BEGIN:VCALENDAR\",",
    "    \"VERSION:2.0\",",
    "    \"PRODID:-//Stadt Neu-Ulm//Abfallkalender 2026//DE\",",
    "    \"CALSCALE:GREGORIAN\",",
    "    \"METHOD:PUBLISH\",",
    "    `X-WR-CALNAME:Abfallkalender ${bezirk} (Neu-Ulm 2026)`,",
    "  ];",
    "  for (const [iso, code] of events) {",
    "    const ymd = iso.replace(/-/g, \"\");",
    "    const summary = TYPE_BY_CODE[code] ?? code;",
    "    out.push(",
    "      \"BEGIN:VEVENT\",",
    "      `UID:${iso}-${code}-bz${bezirk}@neu-ulm-app`,",
    "      \"DTSTAMP:20251119T000000Z\",",
    "      `DTSTART;VALUE=DATE:${ymd}`,",
    "      `SUMMARY:${summary}`,",
    "      \"TRANSP:TRANSPARENT\",",
    "      \"END:VEVENT\",",
    "    );",
    "  }",
    "  out.push(\"END:VCALENDAR\");",
    "  return out.join(\"\\r\\n\");",
    "}",
    "",
    "/** Event count per Bezirk — for sanity checks at boot time. */",
    "export const CALENDAR_2026_COUNTS: Readonly<Record<number, number>> = {",
]
for b in range(1, 9):
    n = len(events_by_bezirk[str(b)])
    ts_lines.append(f"  {b}: {n},")
ts_lines += ["};", ""]

target = "/sessions/stoic-ecstatic-hamilton/mnt/neu-ulm-app/lib/calendar2026.ts"
with open(target, "w", encoding="utf-8") as f:
    f.write("\n".join(ts_lines))
size = os.path.getsize(target)
print(f"Wrote {target}: {size} bytes ({size/1024:.1f} KB)")
